### ISSUE TITLE
Typo, Equation (3-3) of theory manual

### ISSUE THREAD

**Issue by keckler** [dassh-dev/documents#1]
After Equation (3-3) in the theory manual, it says that `\rho = velocity vector`. This should instead read `\rho = material density (kg/m^3)` or something similar.

Also, no units are given for `h` in the same listing. These could be added for consistency.

**Comment by MilosAtz** [comment]
Thanks for catching that, Chris! You're right, of course. I've updated the document and will see about putting out a new version. I'll leave the issue open until I post a new version here.

**Comment by MilosAtz** [comment]
New version uploaded, closing issue. Thanks again!
